title = "Allan Monteiro David"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Rio de Janeiro, Brasil"
email = "allanbrados@gmail.com"
favicon = "/favicon.png"
firstName = "Allan"
lastName = "David"
profileImage = "img/me.png"
showEducation = false
showExperience = false
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = false

[[params.handles]]
link = "https://www.linkedin.com/in/allanbrados/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/allmonty/"
name = "GitHub"

[[params.handles]]
link = "https://gitlab.com/allmonty"
name = "Gitlab"

[[params.handles]]
link = "https://bitbucket.org/allmonty/"
name = "Bitbucket"

[[params.handles]]
link = "https://stackoverflow.com/users/7228231/allan-david"
name = "StackOverflow"

[[params.handles]]
link = "https://www.instagram.com/allmonty/"
name = "Instagram"

[[params.handles]]
link = "https://medium.com/@allmonty"
name = "Medium"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"